### ISSUE TITLE
React app errors - blank page

### ISSUE THREAD

**Issue by W-Ely** [app-generator/flask-react-berry-dashboard#1]
I'm having some trouble getting the react apps to run without error. Specifically https://github.com/app-generator/flask-react-berry-dashboard , https://github.com/app-generator/react-flask-authentication , exc.  I'm running these with the docker/docker compose supplied and with the flask backend up and running.

The react server (docker image) starts without error. But within the browser only a blank page loads, redirecting to http://localhost:3000/dashboard/default I believe as expected, but there is only a blank page and the browser console presents a few errors.

I've tried locking all the depends inside the package.json file rather than floating them but get the same result.

Node version `14.x` from https://github.com/app-generator/flask-react-soft-dashboard/blob/main/react-ui/Dockerfile#L2 I've also tried with `16.x` by changing the base image and rebuilding.

This happens under both the latest stable chrome and brave browsers.

Browser console errors:
```
Material-UI: The `styles` argument provided is invalid.
You are providing a function without a theme in the context.
One of the parent elements needs to use a ThemeProvider.
console.<computed> @ index.js:1
create @ getStylesCreator.js:24
attach @ makeStyles.js:95
(anonymous) @ makeStyles.js:233
useSynchronousEffect @ makeStyles.js:187
useStyles @ makeStyles.js:225
MainLayout @ index.js:80
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
beginWork$1 @ react-dom.development.js:23940
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
enqueueSetState @ react-dom.development.js:12467
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:365
(anonymous) @ react.js:61
dispatch @ redux.js:297
rehydrate @ persistStore.js:79
_rehydrate @ persistReducer.js:61
(anonymous) @ persistReducer.js:90
Promise.then (async)
(anonymous) @ persistReducer.js:89
Promise.then (async)
(anonymous) @ persistReducer.js:84
combination @ redux.js:528
dispatch @ redux.js:288
persist @ persistStore.js:114
persistStore @ persistStore.js:123
(anonymous) @ index.js:8
./src/store/index.js @ index.js:11
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
(anonymous) @ config.js:12
./src/index.js @ index.js:35
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
1 @ GuestGuard.js:31
__webpack_require__ @ bootstrap:856
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1

index.js:1 Material-UI: The `styles` argument provided is invalid.
You are providing a function without a theme in the context.
One of the parent elements needs to use a ThemeProvider.
console.<computed> @ index.js:1
create @ getStylesCreator.js:24
attach @ makeStyles.js:95
(anonymous) @ makeStyles.js:233
useSynchronousEffect @ makeStyles.js:187
useStyles @ makeStyles.js:225
MainLayout @ index.js:80
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
enqueueSetState @ react-dom.development.js:12467
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:365
(anonymous) @ react.js:61
dispatch @ redux.js:297
rehydrate @ persistStore.js:79
_rehydrate @ persistReducer.js:61
(anonymous) @ persistReducer.js:90
Promise.then (async)
(anonymous) @ persistReducer.js:89
Promise.then (async)
(anonymous) @ persistReducer.js:84
combination @ redux.js:528
dispatch @ redux.js:288
persist @ persistStore.js:114
persistStore @ persistStore.js:123
(anonymous) @ index.js:8
./src/store/index.js @ index.js:11
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
(anonymous) @ config.js:12
./src/index.js @ index.js:35
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
1 @ GuestGuard.js:31
__webpack_require__ @ bootstrap:856
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1

getStylesCreator.js:28 Uncaught TypeError: Cannot read properties of undefined (reading 'background')
    at index.js:30:1
    at Object.create (getStylesCreator.js:19:1)
    at attach (makeStyles.js:95:1)
    at makeStyles.js:233:1
    at useSynchronousEffect (makeStyles.js:187:1)
    at useStyles (makeStyles.js:225:1)
    at MainLayout (index.js:80:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21893:1)
    at Object.enqueueSetState (react-dom.development.js:12467:1)
    at PersistGate.push../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:365:1)
    at react.js:61:1
    at Object.dispatch (redux.js:297:1)
    at Object.rehydrate (persistStore.js:79:1)
    at _rehydrate (persistReducer.js:61:1)
    at persistReducer.js:90:1
(anonymous) @ index.js:30
create @ getStylesCreator.js:19
attach @ makeStyles.js:95
(anonymous) @ makeStyles.js:233
useSynchronousEffect @ makeStyles.js:187
useStyles @ makeStyles.js:225
MainLayout @ index.js:80
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
enqueueSetState @ react-dom.development.js:12467
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:365
(anonymous) @ react.js:61
dispatch @ redux.js:297
rehydrate @ persistStore.js:79
_rehydrate @ persistReducer.js:61
(anonymous) @ persistReducer.js:90
Promise.then (async)
(anonymous) @ persistReducer.js:89
Promise.then (async)
(anonymous) @ persistReducer.js:84
combination @ redux.js:528
dispatch @ redux.js:288
persist @ persistStore.js:114
persistStore @ persistStore.js:123
(anonymous) @ index.js:8
./src/store/index.js @ index.js:11
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
(anonymous) @ config.js:12
./src/index.js @ index.js:35
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
1 @ GuestGuard.js:31
__webpack_require__ @ bootstrap:856
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1

index.js:1 The above error occurred in the <MainLayout> component:

    at MainLayout (http://localhost:3000/static/js/main.chunk.js:6097:5)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:195202:29)
    at MainRoutes (http://localhost:3000/static/js/main.chunk.js:7587:88)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:195404:29)
    at Routes
    at NavigationScroll (http://localhost:3000/static/js/main.chunk.js:6589:5)
    at C (http://localhost:3000/static/js/vendors~main.chunk.js:195459:37)
    at InnerThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:56723:74)
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:52626:5)
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:56743:5)
    at StyledEngineProvider (http://localhost:3000/static/js/vendors~main.chunk.js:52889:5)
    at App (http://localhost:3000/static/js/main.chunk.js:125:88)
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:194833:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:194454:35)
    at PersistGate (http://localhost:3000/static/js/vendors~main.chunk.js:202770:5)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:191701:20)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
logCapturedError @ react-dom.development.js:20085
update.callback @ react-dom.development.js:20118
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20736
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
enqueueSetState @ react-dom.development.js:12467
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:365
(anonymous) @ react.js:61
dispatch @ redux.js:297
rehydrate @ persistStore.js:79
_rehydrate @ persistReducer.js:61
(anonymous) @ persistReducer.js:90
Promise.then (async)
(anonymous) @ persistReducer.js:89
Promise.then (async)
(anonymous) @ persistReducer.js:84
combination @ redux.js:528
dispatch @ redux.js:288
persist @ persistStore.js:114
persistStore @ persistStore.js:123
(anonymous) @ index.js:8
./src/store/index.js @ index.js:11
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
(anonymous) @ config.js:12
./src/index.js @ index.js:35
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
1 @ GuestGuard.js:31
__webpack_require__ @ bootstrap:856
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1

index.js:30 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'background')
    at index.js:30:1
    at Object.create (getStylesCreator.js:19:1)
    at attach (makeStyles.js:95:1)
    at makeStyles.js:233:1
    at useSynchronousEffect (makeStyles.js:187:1)
    at useStyles (makeStyles.js:225:1)
    at MainLayout (index.js:80:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21893:1)
    at Object.enqueueSetState (react-dom.development.js:12467:1)
    at PersistGate.push../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:365:1)
    at react.js:61:1
    at Object.dispatch (redux.js:297:1)
    at Object.rehydrate (persistStore.js:79:1)
    at _rehydrate (persistReducer.js:61:1)
    at persistReducer.js:90:1
(anonymous) @ index.js:30
create @ getStylesCreator.js:19
attach @ makeStyles.js:95
(anonymous) @ makeStyles.js:233
useSynchronousEffect @ makeStyles.js:187
useStyles @ makeStyles.js:225
MainLayout @ index.js:80
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
enqueueSetState @ react-dom.development.js:12467
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:365
(anonymous) @ react.js:61
dispatch @ redux.js:297
rehydrate @ persistStore.js:79
_rehydrate @ persistReducer.js:61
(anonymous) @ persistReducer.js:90
Promise.then (async)
(anonymous) @ persistReducer.js:89
Promise.then (async)
(anonymous) @ persistReducer.js:84
combination @ redux.js:528
dispatch @ redux.js:288
persist @ persistStore.js:114
persistStore @ persistStore.js:123
(anonymous) @ index.js:8
./src/store/index.js @ index.js:11
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
(anonymous) @ config.js:12
./src/index.js @ index.js:35
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
1 @ GuestGuard.js:31
__webpack_require__ @ bootstrap:856
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
webpackHotDevClient.js:138 src/layout/MainLayout/Header/ProfileSection/index.js
  Line 130:27:  'setSelectedIndex' is assigned a value but never used  no-unused-vars
printWarnings @ webpackHotDevClient.js:138
handleWarnings @ webpackHotDevClient.js:143
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210

VM217:2 Uncaught ReferenceError: process is not defined
    at Object.4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at Object.8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at Object.8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at HTMLIFrameElement.e.onload (index.js:1:1)
4043 @ VM217:2
r @ VM217:2
8048 @ VM217:2
r @ VM217:2
8641 @ VM217:2
r @ VM217:2
(anonymous) @ VM217:2
(anonymous) @ VM217:2
(anonymous) @ VM217:2
e.onload @ index.js:1
be @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
load (async)
be @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
Promise.then (async)
(anonymous) @ index.js:1
(anonymous) @ index.js:1
l @ index.js:1
```

**Comment by app-generator** [comment]
Hello @W-Ely, 

Please use the latest version. 
P.S. Sorry for this late reply, somehow the notification was unseen. 

🚀🚀
